version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file pdf2txt.yaml --s3-bucket prj2-artifacts-bucket --output-template-file lambdaoutput.yaml

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml
